### ISSUE TITLE
Generate vmware vsphere provider

### ISSUE THREAD

**Issue by kasey** [crossplane-contrib/terraform-provider-gen#1]
### What problem are you facing?

In order to push terraform-provider-gen to generalize for other providers, and to test the value of it for long-tail providers, generate a provider for a provider that isn't aws/gcp/azure.

### How could Crossplane help solve your problem?

We should consider how widely used terraform providers are in this decision. In looking at the ranking of terraform providers in the registry by downloads, the top provider that covers a cloud-like use case is [vmware vsphere](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs) at about 2 million downloads. 

A vsphere simulator called [vcsim](https://github.com/vmware/govmomi/tree/master/vcsim) is available to aid in testing. As we do not have expertise in vsphere or an active environment, this project will initially be used for development and testing.

**Comment by grantgumina** [comment]
@jbw976 I believe we can close this?

**Comment by jbw976** [comment]
This provider has been released/published and blogged about here: https://blog.crossplane.io/adding-vmware-support-to-crossplane-using-terraform/

Great work @kasey! 💪
